sudo: required
language: python
python:
  - 3.4
  
before_install:
    - pip install pytest pytest-cov
    - pip install numpy
    - pip install coveralls

install:
  - pip3 install http://download.pytorch.org/whl/cpu/torch-0.4.1-cp36-cp36m-linux_x86_64.whl 
  - python setup.py install


script: py.test --cov

after_success:
    - coveralls

notifications:
  email: false
